get_filename_component(PSI_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
message(STATUS "Linking to psi package in ${PSI_CMAKE_DIR}")
set(PSI_INCLUDE_DIRS "@ALL_INCLUDE_DIRS@")
if(NOT TARGET libpsi AND EXISTS "${PSI_CMAKE_DIR}/PsiCTargets.cmake")
  include("${PSI_CMAKE_DIR}/PsiCTargets.cmake")
endif()
if(NOT TARGET psi AND EXISTS "${PSI_CMAKE_DIR}/PsiCPPTargets.cmake")
  include("${PSI_CMAKE_DIR}/PsiCPPTargets.cmake")
endif()

unset(PSI_LIBRARIES)
if(TARGET psi)
  list(APPEND PSI_LIBRARIES psi)
  set(PSI_CPP_LIBRARY psi)
endif()
if(TARGET libpsi)
  list(APPEND PSI_LIBRARIES libpsi)
  set(PSI_C_LIBRARY libpsi)
endif()
set(PSI_ABOUT_EXECUTABLE psi_about)
set(PSI_HAS_MPI @PSI_MPI@)
